import {useEffect,useMemo,useState} from 'react';
const KEY='fra-field-evidence-queue-v1';
const stored=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'[]')}catch{return[]}};
export default function FieldVerification({claim,api,onChanged}){
 const[tasks,setTasks]=useState([]),[queue,setQueue]=useState(stored),[offline,setOffline]=useState(false),[observation,setObservation]=useState(''),[photo,setPhoto]=useState('DEMO-PHOTO-REFERENCE'),[latitude,setLatitude]=useState(''),[longitude,setLongitude]=useState('');const online=!offline&&navigator.onLine;const active=useMemo(()=>tasks[0],[tasks]);
 const load=()=>claim&&fetch(`${api}/api/claims/${claim.claim_id}/field-verification`).then(r=>{if(!r.ok)throw Error();return r.json()}).then(x=>setTasks(x.data||[])).catch(()=>setTasks([]));
 useEffect(()=>{load()},[claim?.claim_id]);useEffect(()=>localStorage.setItem(KEY,JSON.stringify(queue)),[queue]);
 const sync=async item=>{if(!online)return;setQueue(rows=>rows.map(x=>x.local_id===item.local_id?{...x,sync_state:'SYNCING'}:x));try{const response=await fetch(`${api}/api/claims/${item.claim_id}/field-verification/${item.verification_id}/evidence`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(item.payload)});if(!response.ok)throw Error();setQueue(rows=>rows.map(x=>x.local_id===item.local_id?{...x,sync_state:'SYNCED'}:x));load();onChanged?.()}catch{setQueue(rows=>rows.map(x=>x.local_id===item.local_id?{...x,sync_state:'SYNC_ERROR'}:x))}};
 useEffect(()=>{if(online)queue.filter(x=>['LOCAL','QUEUED','SYNC_ERROR'].includes(x.sync_state)).forEach(sync)},[online]);
 const capture=e=>{e.preventDefault();if(!active)return;const item={local_id:crypto.randomUUID(),claim_id:claim.claim_id,verification_id:active.verification_id,sync_state:online?'QUEUED':'LOCAL',payload:{evidence_type:'FIELD_PHOTO',photo_reference:photo,photo_metadata:{data_label:'SYNTHETIC DEMO DATA'},latitude:latitude===''?null:Number(latitude),longitude:longitude===''?null:Number(longitude),captured_at:new Date().toISOString(),observation,notes:'',submitted_by:'FIELD_WORKER_DEMO'}};setQueue(rows=>[...rows,item]);setObservation('');if(online)setTimeout(()=>sync(item),0)};
 const entries=queue.filter(x=>x.claim_id===claim?.claim_id);return <section className="panel field-verification"><div className="panel-head"><div><p className="eyebrow">FIELD VERIFICATION</p><h2>Human evidence capture</h2><p className="muted">Synthetic demo metadata only. Human review remains required.</p></div><button onClick={()=>setOffline(x=>!x)}>{offline?'Offline (simulated)':'Online'}</button></div><p className={`connection ${online?'online':'offline'}`}>{online?'Online — queued evidence will synchronize.':'Offline — evidence remains queued on this device.'}</p>{tasks.length?<><div className="task-list">{tasks.map(task=><div className="field-task" key={task.verification_id}><strong>{task.assigned_to}</strong><span>{task.status||'PENDING'}</span><p>{task.reason||task.observation||'Evidence requires verification.'}</p></div>)}</div><form className="field-form" onSubmit={capture}><label>Observation<textarea required value={observation} onChange={e=>setObservation(e.target.value)}/></label><label>Demo photo reference<input required value={photo} onChange={e=>setPhoto(e.target.value)}/></label><div className="coordinates"><label>Latitude<input type="number" min="-90" max="90" value={latitude} onChange={e=>setLatitude(e.target.value)}/></label><label>Longitude<input type="number" min="-180" max="180" value={longitude} onChange={e=>setLongitude(e.target.value)}/></label></div><button>Capture evidence</button></form></>:<p className="empty">No field verification task is currently assigned.</p>}<h3>Offline evidence queue</h3>{entries.length?entries.map(item=><div className="queue-item" key={item.local_id}><span>{item.payload.observation}</span><strong>{item.sync_state.replaceAll('_',' ')}</strong>{online&&item.sync_state!=='SYNCED'&&<button onClick={()=>sync(item)}>Sync now</button>}</div>):<p className="muted">No locally queued evidence.</p>}</section>
}
