import { useEffect, useMemo, useRef, useState } from 'react'
import L from 'leaflet'
import { GeoJSON, LayersControl, MapContainer, Marker, Popup, TileLayer, useMap } from 'react-leaflet'
import 'leaflet/dist/leaflet.css'

const colors = ['#45c8da', '#f0b34e', '#e873a8', '#a97aea', '#62ce89', '#f4844d', '#6fa9e9', '#db745d']
const geometryBounds = geometry => { try { const value = L.geoJSON(geometry).getBounds(); return value.isValid() ? value : null } catch { return null } }
const positionFor = feature => Number.isFinite(feature.properties?.latitude) && Number.isFinite(feature.properties?.longitude) ? [feature.properties.latitude, feature.properties.longitude] : null
const markerIcon = (claim, color) => L.divIcon({ className: 'case-marker-wrap', html: `<span class="case-marker" style="--case-color:${color}">${claim}</span>`, iconSize: [106, 29], iconAnchor: [53, 15] })
function MapCamera({ cases, focused, reset }) { const map = useMap(); const didFit = useRef(false); const allIndia = () => { const bounds = L.latLngBounds([]); cases.forEach(item => { const point = positionFor(item); if (point) bounds.extend(point) }); if (bounds.isValid()) map.fitBounds(bounds, { padding: [60, 60], maxZoom: 5, animate: true }) }; useEffect(() => { if (!didFit.current && cases.length) { allIndia(); didFit.current = true } }, [cases]); useEffect(() => { if (!focused) return; const point = positionFor(focused); if (point) map.flyTo(point, 11, { duration: 1.15 }) }, [focused, map]); useEffect(() => { if (reset) allIndia() }, [reset]); return null }
function CaseBoundaries({ cases, focus }) { return <>{cases.map((item, index) => { const active = focus?.claim_id === item.properties.claim_id; return <GeoJSON key={item.properties.claim_id} data={item} style={{ color: colors[index % colors.length], fillColor: colors[index % colors.length], fillOpacity: active ? .35 : .12, weight: active ? 3 : 1.5 }} /> })}</> }
export default function MapView({ api, onOpenCase, focusClaimId }) {
  const [cases, setCases] = useState([]); const [focused, setFocused] = useState(null); const [search, setSearch] = useState(''); const [reset, setReset] = useState(0); const [error, setError] = useState('')
  useEffect(() => { let active = true; fetch(`${api}/api/map/claims`).then(response => response.ok ? response.json() : Promise.reject()).then(data => { if (active) setCases(data.features || []) }).catch(() => setError('Cases could not be loaded. Start the local API and try again.')); return () => { active = false } }, [api])
  useEffect(() => { if (!focusClaimId || !cases.length) return; const match = cases.find(item => item.properties.claim_id === focusClaimId); if (match) setFocused(match) }, [focusClaimId, cases])
  const visibleCases = useMemo(() => { const term = search.trim().toLowerCase(); return !term ? cases : cases.filter(item => `${item.properties.claim_id} ${item.properties.village} ${item.properties.district} ${item.properties.state} ${item.properties.claimant_reference}`.toLowerCase().includes(term)) }, [cases, search])
  useEffect(() => { if (search.trim() && visibleCases.length === 1) setFocused(visibleCases[0]) }, [search, visibleCases])
  const choose = item => setFocused(item)
  const resetView = () => { setFocused(null); setSearch(''); setReset(value => value + 1) }
  return <div className="india-map-shell">{error && <div className="map-error">{error}</div>}<MapContainer center={[22, 79]} zoom={5} className="india-leaflet-map" scrollWheelZoom><TileLayer attribution="Tiles &copy; Esri" url={import.meta.env.VITE_TILE_URL || 'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}'} /><MapCamera cases={cases} focused={focused} reset={reset} /><LayersControl position="topright"><LayersControl.Overlay checked name="Case boundaries"><CaseBoundaries cases={visibleCases} focus={focused?.properties} /></LayersControl.Overlay><LayersControl.Overlay checked name="Case markers">{visibleCases.map((item, index) => { const point = positionFor(item); const p = item.properties; return point ? <Marker key={p.claim_id} position={point} icon={markerIcon(p.claim_id, colors[index % colors.length])} eventHandlers={{ click: () => choose(item) }}><Popup><strong>{p.claim_id}</strong><dl className="case-popup"><dt>Case</dt><dd>{p.claimant_reference || p.village}</dd><dt>State</dt><dd>{p.state}</dd><dt>District</dt><dd>{p.district}</dd><dt>Evidence</dt><dd>{p.status}</dd><dt>Verification</dt><dd>{p.verification_status}</dd></dl><button onClick={() => onOpenCase(p.claim_id)}>View Case</button></Popup></Marker> : null })}</LayersControl.Overlay></LayersControl></MapContainer>
    <div className="map-toolbar"><label><span>⌕</span><input value={search} onChange={event => setSearch(event.target.value)} placeholder="Claim ID, state, district or case name" aria-label="Search all cases" /></label><button onClick={resetView}>Show All India</button></div><aside className="map-legend"><b>FRA case locations</b><span><i className="swatch" />Case marker</span><small>{cases.length} cases · click a marker for details</small></aside><p className="map-title">INDIA · FRA EVIDENCE MAP</p>
  </div>
}
